version: '2'

services:

  tensorflow:
    build: .
    entrypoint: ["/usr/bin/python3", "word_rnn.py"]
    restart: always
    environment:
      - "TENSORBOARD_LOGS_DIR=/tensorboard_logs"
      - "MODELS_DIR=/models/"
    env_file:
      - env
    volumes:
      - tensorboard-logs-volume:/tensorboard_logs/
      - ./models/:/models/
      - ./data/:/data/

  tensorboard:
    build: .
    restart: always
    ports:
      - "80:6006"
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - tensorboard-logs-volume:/tensorboard_logs/
    entrypoint: ["tensorboard",  "--logdir=/tensorboard_logs/", "--host=0.0.0.0", "--port=6006"]

volumes:
  tensorboard-logs-volume: